version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php8.1/Dockerfile
        container_name: dicnovel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        networks:
            dicnovel_backend:
                ipv4_address: 175.25.0.10
#        environment:
#            DB_CONNECTION: mysql
#            DB_HOST: dicnovel_db
#            DB_PORT: 3306
#            DB_DATABASE: dicnovel
#            DB_USERNAME: root
#            DB_PASSWORD: Idsa32ADsaWsdawW

    db:
        image: mysql:5.7
        container_name: dicnovel_db
        environment:
            MYSQL_ROOT_PASSWORD: Idsa32ADsaWsdawW
            MYSQL_DATABASE: dicnovel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            dicnovel_backend:
                ipv4_address: 175.25.0.11

networks:
    dicnovel_backend:
        driver: bridge
        ipam:
            config:
                - subnet: 175.25.0.0/16
                  gateway: 175.25.5.254

volumes:
    db_data:
